language: node_js
node_js:
    - stable
branches:
    only:
    - develop
script:
    - npm test
    - npm run build
env:
    global:
    - GH_REPO: github.com/${TRAVIS_REPO_SLUG}
    - secure: MN9+sX70CtI9IJZdYNNJq86gXcLnf457dvEh0fHjdiFqc55mP6+SX5wa9gHq6YVHgsWTomr2BK3olo50YAPvZCxFuWAL5RiNNM/aZU0PfAQESuYpDdfnGc36ckWetKJNB6gJFp4g3IkO1TbNcqySQzHzXFEiiiPyNBDdLM4Qmpk=
after_success:
    - npm run deploy

