language: node_js
node_js:
    - stable
branches:
    only:
    - develop
script:
    - npm test
    - npm run build
env:
    global:
    - GH_REPO: github.com/${TRAVIS_REPO_SLUG}
    - secure: hm26s+1RR8mqgjCcEX7jubNtwZ22IINDFk8G4iXB46ddzyrI9QJwMmZoiV8b7FQ14AsphrhuV6LkGLGiZwThyj4aNza5MWQcz+EW7M1a9srSvOggCQyE0FLB3dEsOoQKTFzV5ULH+lGlKZrkAOTMSf+cU7u8ZVtGrUC+fndELyM=
after_success:
    - npm run deploy

