language: node_js
node_js:
    - stable
branches:
    only:
    - develop
script:
    - npm test
    - npm run build
env:
    global:
    - GH_REPOSITORY: github.com/${TRAVIS_REPO_SLUG}
    - secure: aXnbZuKQo7mzaipfDZdgPfHWnBX+v8JWr9vLPFo/qMDzpBAJx+aAaijL+1YnmWGysKtAIJ64/jF7nU+La8QNmJWAQEJ3iEFwwl28FcBO+Te4f0DB0M85SXg8R+oG5cAl66KhF1HyZqQUgNa5bW1hKRVwrmFOq0CqIDAXceHiTAw=
after_success:
    - npm run deploy

